/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserUpdateUserImport } from './routes/user/update-user'
import { Route as UserCreateUserImport } from './routes/user/create-user'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUpdateUserRoute = UserUpdateUserImport.update({
  id: '/user/update-user',
  path: '/user/update-user',
  getParentRoute: () => rootRoute,
} as any)

const UserCreateUserRoute = UserCreateUserImport.update({
  id: '/user/create-user',
  path: '/user/create-user',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/user/create-user': {
      id: '/user/create-user'
      path: '/user/create-user'
      fullPath: '/user/create-user'
      preLoaderRoute: typeof UserCreateUserImport
      parentRoute: typeof rootRoute
    }
    '/user/update-user': {
      id: '/user/update-user'
      path: '/user/update-user'
      fullPath: '/user/update-user'
      preLoaderRoute: typeof UserUpdateUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/create-user': typeof UserCreateUserRoute
  '/user/update-user': typeof UserUpdateUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/create-user': typeof UserCreateUserRoute
  '/user/update-user': typeof UserUpdateUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/user/create-user': typeof UserCreateUserRoute
  '/user/update-user': typeof UserUpdateUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user/create-user' | '/user/update-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user/create-user' | '/user/update-user'
  id: '__root__' | '/' | '/user/create-user' | '/user/update-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserCreateUserRoute: typeof UserCreateUserRoute
  UserUpdateUserRoute: typeof UserUpdateUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserCreateUserRoute: UserCreateUserRoute,
  UserUpdateUserRoute: UserUpdateUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user/create-user",
        "/user/update-user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user/create-user": {
      "filePath": "user/create-user.tsx"
    },
    "/user/update-user": {
      "filePath": "user/update-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
